# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projek.ui',
# licensing of 'projek.ui' applies.
#
# Created: Mon Jun 24 19:02:10 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_daftar_pengunjung(object):
    def setupUi(self, daftar_pengunjung):
        daftar_pengunjung.setObjectName("daftar_pengunjung")
        daftar_pengunjung.resize(782, 516)
        self.centralwidget = QtWidgets.QWidget(daftar_pengunjung)
        self.centralwidget.setObjectName("centralwidget")
        self.frm_masukan = QtWidgets.QFrame(self.centralwidget)
        self.frm_masukan.setGeometry(QtCore.QRect(20, 10, 321, 181))
        self.frm_masukan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_masukan.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_masukan.setObjectName("frm_masukan")
        self.txt_antrian = QtWidgets.QLineEdit(self.frm_masukan)
        self.txt_antrian.setGeometry(QtCore.QRect(90, 140, 113, 20))
        self.txt_antrian.setPlaceholderText("")
        self.txt_antrian.setObjectName("txt_antrian")
        self.label = QtWidgets.QLabel(self.frm_masukan)
        self.label.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frm_masukan)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 47, 13))
        self.label_4.setObjectName("label_4")
        self.txt_nama = QtWidgets.QLineEdit(self.frm_masukan)
        self.txt_nama.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.txt_nama.setObjectName("txt_nama")
        self.txt_id = QtWidgets.QLineEdit(self.frm_masukan)
        self.txt_id.setGeometry(QtCore.QRect(112, 80, 91, 20))
        self.txt_id.setObjectName("txt_id")
        self.label_3 = QtWidgets.QLabel(self.frm_masukan)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frm_masukan)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.label_2.setObjectName("label_2")
        self.txt_alamat = QtWidgets.QLineEdit(self.frm_masukan)
        self.txt_alamat.setGeometry(QtCore.QRect(90, 110, 113, 20))
        self.txt_alamat.setObjectName("txt_alamat")
        self.label_5 = QtWidgets.QLabel(self.frm_masukan)
        self.label_5.setGeometry(QtCore.QRect(20, 15, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_tambah = QtWidgets.QPushButton(self.frm_masukan)
        self.btn_tambah.setGeometry(QtCore.QRect(220, 140, 81, 23))
        self.btn_tambah.setObjectName("btn_tambah")
        self.label_6 = QtWidgets.QLabel(self.frm_masukan)
        self.label_6.setGeometry(QtCore.QRect(90, 80, 21, 16))
        self.label_6.setObjectName("label_6")
        self.btn_tampilkan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tampilkan.setGeometry(QtCore.QRect(350, 10, 81, 23))
        self.btn_tampilkan.setObjectName("btn_tampilkan")
        self.txt_cari = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cari.setGeometry(QtCore.QRect(250, 220, 131, 21))
        self.txt_cari.setObjectName("txt_cari")
        self.btn_cari = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cari.setGeometry(QtCore.QRect(390, 220, 41, 23))
        self.btn_cari.setObjectName("btn_cari")
        self.btn_urut = QtWidgets.QPushButton(self.centralwidget)
        self.btn_urut.setGeometry(QtCore.QRect(20, 220, 91, 23))
        self.btn_urut.setObjectName("btn_urut")
        self.btn_queue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_queue.setGeometry(QtCore.QRect(690, 240, 71, 23))
        self.btn_queue.setObjectName("btn_queue")
        self.tree_data = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_data.setGeometry(QtCore.QRect(350, 40, 411, 151))
        self.tree_data.setObjectName("tree_data")
        self.tree_hasil = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_hasil.setGeometry(QtCore.QRect(20, 250, 411, 221))
        self.tree_hasil.setObjectName("tree_hasil")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(440, 370, 321, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label_7.setObjectName("label_7")
        self.txt_stack = QtWidgets.QLineEdit(self.frame)
        self.txt_stack.setGeometry(QtCore.QRect(90, 30, 211, 20))
        self.txt_stack.setObjectName("txt_stack")
        self.btn_stack = QtWidgets.QPushButton(self.frame)
        self.btn_stack.setGeometry(QtCore.QRect(10, 30, 61, 23))
        self.btn_stack.setObjectName("btn_stack")
        self.txt_hasilstack = QtWidgets.QLabel(self.frame)
        self.txt_hasilstack.setGeometry(QtCore.QRect(90, 60, 211, 21))
        self.txt_hasilstack.setAutoFillBackground(False)
        self.txt_hasilstack.setFrameShape(QtWidgets.QFrame.Box)
        self.txt_hasilstack.setText("")
        self.txt_hasilstack.setObjectName("txt_hasilstack")
        self.tree_queue = QtWidgets.QTreeWidget(self.centralwidget)
        self.tree_queue.setGeometry(QtCore.QRect(440, 270, 321, 91))
        self.tree_queue.setObjectName("tree_queue")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(440, 250, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        daftar_pengunjung.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(daftar_pengunjung)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        daftar_pengunjung.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(daftar_pengunjung)
        self.statusbar.setObjectName("statusbar")
        daftar_pengunjung.setStatusBar(self.statusbar)

        self.retranslateUi(daftar_pengunjung)
        QtCore.QMetaObject.connectSlotsByName(daftar_pengunjung)

    def retranslateUi(self, daftar_pengunjung):
        daftar_pengunjung.setWindowTitle(QtWidgets.QApplication.translate("daftar_pengunjung", "Daftar Pengunjung", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Nama", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Antrian", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Alamat", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "ID", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Masukkan Data", None, -1))
        self.btn_tambah.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Menambahkan", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "D - ", None, -1))
        self.btn_tampilkan.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Tampilkan Data", None, -1))
        self.txt_cari.setPlaceholderText(QtWidgets.QApplication.translate("daftar_pengunjung", "Masukkan ID", None, -1))
        self.btn_cari.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Cari", None, -1))
        self.btn_urut.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Urutkan ID", None, -1))
        self.btn_queue.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Tekan disini", None, -1))
        self.tree_data.headerItem().setText(0, QtWidgets.QApplication.translate("daftar_pengunjung", "Nama", None, -1))
        self.tree_data.headerItem().setText(1, QtWidgets.QApplication.translate("daftar_pengunjung", "ID", None, -1))
        self.tree_data.headerItem().setText(2, QtWidgets.QApplication.translate("daftar_pengunjung", "Alamat", None, -1))
        self.tree_data.headerItem().setText(3, QtWidgets.QApplication.translate("daftar_pengunjung", "Antrian", None, -1))
        self.tree_hasil.headerItem().setText(0, QtWidgets.QApplication.translate("daftar_pengunjung", "Nama", None, -1))
        self.tree_hasil.headerItem().setText(1, QtWidgets.QApplication.translate("daftar_pengunjung", "ID", None, -1))
        self.tree_hasil.headerItem().setText(2, QtWidgets.QApplication.translate("daftar_pengunjung", "Alamat", None, -1))
        self.tree_hasil.headerItem().setText(3, QtWidgets.QApplication.translate("daftar_pengunjung", "Antrian", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Mengubah ID menjadi Bilangan Hexa", None, -1))
        self.txt_stack.setPlaceholderText(QtWidgets.QApplication.translate("daftar_pengunjung", "Masukkan ID", None, -1))
        self.btn_stack.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Ubah", None, -1))
        self.tree_queue.headerItem().setText(0, QtWidgets.QApplication.translate("daftar_pengunjung", "Nama", None, -1))
        self.tree_queue.headerItem().setText(1, QtWidgets.QApplication.translate("daftar_pengunjung", "ID", None, -1))
        self.tree_queue.headerItem().setText(2, QtWidgets.QApplication.translate("daftar_pengunjung", "Alamat", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("daftar_pengunjung", "Urutan Antrian", None, -1))

